name: Deploy to Heroku

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://strava2kilometrikisa.herokuapp.com/
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run test
      - run: npm run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'strava2kilometrikisa'
          heroku_email: 'salmi.tuomas@gmail.com'
