name: Deploy to Google App Engine

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: GCP production deployment
      url: https://strava2kilometrikisa.ey.r.appspot.com/
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: 'actions/checkout@v3'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test
      - run: npm run build

      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0
